language: python
cache: pip
sudo: false
env:
  global:
  - PACKAGENAME="htsimaging"
  - CONDA_DEPS="pip flake8 pytest numpy scipy matplotlib pandas opencv scikit-bio"
  - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
python:
- '2.7'
before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda config --add channels biocore
- conda config --add channels conda-forge
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- travis_retry pip install $PIP_DEPS
- conda env create -f environment.yml
- pip install dms2dfe
- pip install https://github.com/soft-matter/pims_nd2/archive/v1.0.zip
install:
- python setup.py install --record installed_files.txt
script:
- pytest test/test_pkg.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: rraadd88
  distributions: sdist bdist_wheel
  # server: https://upload.pypi.org/legacy/
  password:
    secure: jv6ZE7KYoAJN+pjwFoDXwI/emTeo/Ysue+UHwt83Qjd3C5DREBWbHrvZtll55xCG98f3fkEkUxH0vju+QY26Eo++qFMoozbeGqtrRUhV+ithTXMVjEXcQxPOzN/cfqay6gqr89i7rjdQVzEj76rX5akixoSTJTrEwXKy0swBCwIDZW3zZ+uDMnElagVLCrCtG0HASpXfmxuTyM9XczolKIqQOG/9MNtQv96DE032K/1lY6XJ+uGCeIdQ/HutgGxAhHp9CUAZztPk9CmNRGoUGcFocyQiaCJckWifd9HgRz65vN+P602GRUBEY0xm8hJpm6vrKfKUL1bEvYkEHqzbDJesJCPcUwUODzDP046Ozkv5iYqBGmJI269f7yYVyVrbG8eRoVF7DHEznWeQL9njMdR4DzY9M4M+lPCJ2AqgAqQyml/V5Ntq30RRU8Lor749slAPDzMfmYjiHPO+AVrfIL2YugNLVMmUWVWWnJjT3W9EhXmlxPyheQiksyBP8eqZLrpAxzoWTVVCfacilNRd85NEtV02YOiEQkOmx1fixF8LWLuTU0chByfOvNTLRbiF+n0vKz+9NRjwJbYLE9e+0MvFPU9f3dZ9bLvQEHBCPAPXoTPHF1aSl14CQFdRk6u9qFXDzf/HSBWCB9DC2Ru8p+IliGWx5DJy602Bqm14VP8=
  # on:
  #   tags: true
  #   branch: master