name: htsimaging
channels:
- conda-forge
- biocore
- bioconda
dependencies:
- python=3.6
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- pip:
  - scikit-bio
  - git+git+https://github.com/rraadd88/rohan
